name: Check Appointments

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 Minutes
    - cron: '*/5 * * * *'  # Runs every 5 Minutes
  workflow_dispatch:    # Allows manual trigger of the workflow

jobs:
  check-appointments:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_BOT_SECRET }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
      - name: Install Chrome
        run: |
          wget -q -O google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
      - name: Install ChromeDriver
        run: |
          wget -q -O chromedriver_linux64.zip https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium
      - name: Run script
        run: |
          python main.py 2>&1 | tee log.txt
      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt